/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'streamline-ultimate-color:messages-people-user-bubble-circle'
    }
  },
  {
    name: 'chat-history',
    path: '/chat-history',
    component: 'layout.base$view.chat-history',
    meta: {
      title: 'chat-history',
      i18nKey: 'route.chat-history',
      roles: ['ADMIN'],
      icon: 'streamline-ultimate-color:paper-write',
      order: 2
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'invite-code',
    path: '/invite-code',
    component: 'layout.base$view.invite-code',
    meta: {
      title: 'invite-code',
      i18nKey: 'route.invite-code',
      icon: 'streamline-ultimate-color:retouch-face',
      roles: ['ADMIN'],
      order: 6
    }
  },
  {
    name: 'knowledge-base',
    path: '/knowledge-base',
    component: 'layout.base$view.knowledge-base',
    meta: {
      title: 'knowledge-base',
      i18nKey: 'route.knowledge-base',
      icon: 'streamline-ultimate-color:folder-upload',
      order: 3
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'model-provider',
    path: '/model-provider',
    component: 'layout.base$view.model-provider',
    meta: {
      title: 'model-provider',
      i18nKey: 'route.model-provider',
      roles: ['ADMIN']
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      icon: 'streamline-ultimate-color:tags-1',
      roles: ['ADMIN'],
      order: 4
    }
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      icon: 'streamline-ultimate-color:programming-user-chat',
      order: 7
    }
  },
  {
    name: 'recharge',
    path: '/recharge',
    component: 'layout.base$view.recharge',
    meta: {
      title: 'recharge',
      i18nKey: 'route.recharge',
      icon: 'streamline-ultimate-color:shopping-basket-3',
      order: 8
    }
  },
  {
    name: 'recharge-manage',
    path: '/recharge-manage',
    component: 'layout.base$view.recharge-manage',
    meta: {
      title: 'recharge-manage',
      i18nKey: 'route.recharge-manage',
      icon: 'streamline-ultimate-color:shop-sale-1',
      roles: ['ADMIN'],
      order: 9
    }
  },
  {
    name: 'usage-monitor',
    path: '/usage-monitor',
    component: 'layout.base$view.usage-monitor',
    meta: {
      title: 'usage-monitor',
      i18nKey: 'route.usage-monitor',
      icon: 'streamline-ultimate-color:signal-full',
      roles: ['ADMIN'],
      order: 6
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'streamline-ultimate-color:multiple-neutral-2',
      roles: ['ADMIN'],
      order: 1
    }
  }
];
